"""empty message

Revision ID: 02b4d463e24b
Revises: 5ae843c6bf35
Create Date: 2016-02-04 23:24:56.551162

"""

# revision identifiers, used by Alembic.
revision = '02b4d463e24b'
down_revision = '5ae843c6bf35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
